name: freezed_guide_dart
description: A tutorial on using freezed
version: 1.0.0

environment:
  sdk: ^3.4.1

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0


dev_dependencies:

  build_runner: ^2.4.11
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^3.0.0
  test: ^1.24.0
